#!/usr/bin/env python3
"""
Telegram Notification Module for Network Automation
Usage: python3 scripts/telegram_notify.py -t "CRITICAL" -m "BGP peer down on ncs540-core-01"
"""

import argparse
import os
import sys
import json
import urllib.request
import urllib.error
from datetime import datetime


class TelegramNotifier:
    def __init__(self):
        self.bot_token = os.environ.get('TELEGRAM_BOT_TOKEN', '')
        self.chat_id = os.environ.get('TELEGRAM_CHAT_ID', '')
        self.api_url = f"https://api.telegram.org/bot{self.bot_token}/sendMessage"

    def send(self, message, severity="INFO", device=None):
        """Send Telegram notification"""
        if not self.bot_token or not self.chat_id:
            print("ERROR: TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID must be set")
            return False

        # Format message with severity emoji and timestamp
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        severity_emoji = {
            "CRITICAL": "🚨",
            "WARNING": "⚠️",
            "INFO": "ℹ️",
            "SUCCESS": "✅"
        }.get(severity.upper(), "ℹ️")

        formatted_message = f"""
{severity_emoji} *Network Alert - {severity.upper()}*
━━━━━━━━━━━━━━━━━━━━━━━━
📅 {timestamp}
🏷️ Device: {device or 'N/A'}
📝 Message:
{message}
━━━━━━━━━━━━━━━━━━━━━━━━
_Generated by Network Automation_
"""

        payload = json.dumps({
            'chat_id': self.chat_id,
            'text': formatted_message,
            'parse_mode': 'Markdown'
        }).encode('utf-8')

        req = urllib.request.Request(
            self.api_url,
            data=payload,
            headers={'Content-Type': 'application/json'}
        )

        try:
            with urllib.request.urlopen(req, timeout=10) as response:
                result = json.loads(response.read().decode('utf-8'))
                if result.get('ok'):
                    print(f"[OK] Telegram notification sent")
                    return True
                else:
                    print(f"[ERROR] Telegram API error: {result}")
                    return False
        except urllib.error.URLError as e:
            print(f"[ERROR] Failed to send Telegram: {e}")
            return False


def main():
    parser = argparse.ArgumentParser(description='Send Telegram notifications')
    parser.add_argument('-t', '--severity', default='INFO',
                        choices=['CRITICAL', 'WARNING', 'INFO', 'SUCCESS'],
                        help='Alert severity level')
    parser.add_argument('-m', '--message', required=True,
                        help='Alert message')
    parser.add_argument('-d', '--device', default=None,
                        help='Device name')
    parser.add_argument('-b', '--bot-token', default=None,
                        help='Telegram bot token (or set TELEGRAM_BOT_TOKEN)')
    parser.add_argument('-c', '--chat-id', default=None,
                        help='Telegram chat ID (or set TELEGRAM_CHAT_ID)')

    args = parser.parse_args()

    notifier = TelegramNotifier()
    if args.bot_token:
        notifier.bot_token = args.bot_token
    if args.chat_id:
        notifier.chat_id = args.chat_id

    success = notifier.send(args.message, args.severity, args.device)
    sys.exit(0 if success else 1)


if __name__ == '__main__':
    main()